=== liambloom/bjp-checker/ui/src/main/resources/help/help.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0">
    <xs:element name="command" type="command" />

    <xs:complexType name="command">
        <xs:sequence>
            <xs:element name="name" type="xs:string" maxOccurs="unbounded" />
            <xs:element name="description" type="xs:string" />
            <xs:element name="command" type="command" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="arguments" type="arguments" minOccurs="0" />
            <xs:element name="option" type="option" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="note" type="xs:string" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="arguments">
        <xs:sequence>
            <xs:element name="argument" type="argument" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="argument">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="help" type="xs:anyURI" />
                <xs:attribute name="minOccurs" type="lowerBound" />
                <xs:attribute name="maxOccurs" type="upperBound" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="option">
        <xs:sequence>
            <xs:element name="flag" type="xs:string" maxOccurs="unbounded" />
            <xs:element name="description" type="xs:string" />
            <xs:element name="colon" type="colon" minOccurs="0" />
            <xs:element name="arguments" type="arguments" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="required" type="xs:boolean" />
        <xs:attribute name="waterfalls" type="xs:boolean" />
    </xs:complexType>

    <xs:complexType name="colon">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="required" type="xs:boolean" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="lowerBound">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0" />
            <xs:maxInclusive value="1" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="upperBound">
        <xs:restriction base="xs:string">
            <xs:pattern value="unbounded|0*[1-9]\d*" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== liambloom/bjp-checker/ui/src/main/resources/help/help.xml
<?xml version="1.0" encoding="utf-8" ?>
<command
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="file:./help.xsd">
    <name>chk</name>
    <description>foo</description>
    <command>
        <name>-v</name>
        <name>--version</name>
        <description>Prints the version number of the checker</description>
    </command>
    <command>
        <name>check</name>
        <description>Checks programs</description>
        <arguments>
            <argument help="./help/glob.txt">glob</argument>
        </arguments>
        <option required="true">
            <flag>-c</flag>
            <flag>--chapter</flag>
            <description>The chapter number to check</description>
            <arguments>
                <argument>chapter number</argument>
            </arguments>
        </option>
        <option required="true">
            <flag>-t</flag>
            <flag>--target</flag>
            <description>The target checkable type and number(s) to check</description>
            <colon required="true">checkable type</colon>
            <arguments>
                <argument maxOccurs="unbounded">number(s)</argument>
            </arguments>
        </option>
        <option required="true">
            <flag>-b</flag>
            <flag>--book</flag>
            <description>The book to use</description>
            <arguments>
                <argument>book name</argument>
            </arguments>
        </option>
    </command>
    <command>
        <name>books</name>
        <description>Book-related commands</description>
        <command>
            <name>add</name>
            <description>Add a book</description>
            <arguments>
                <argument>name</argument>
                <argument>source</argument>
                <argument>parser</argument>
            </arguments>
        </command>
        <command>
            <name>rename</name>
            <description>Rename a book</description>
            <arguments>
                <argument>old name</argument>
                <argument>new name</argument>
            </arguments>
        </command>
        <command>
            <name>validate</name>
            <description>Validate book(s)</description>
            <arguments>
                <argument maxOccurs="unbounded">book</argument>
            </arguments>
            <note>You can use `-a' or `--all' instead of book names to check all books</note>
        </command>
        <command>
            <name>remove</name>
            <description>Remove a book</description>
            <arguments>
                <argument>name</argument>
            </arguments>
        </command>
        <command>
            <name>move</name>
            <description>Change the URL of a book</description>
            <arguments>
                <argument>name</argument>
                <argument>new URL</argument>
            </arguments>
        </command>
        <command>
            <name>list</name>
            <description>List all books</description>
        </command>
        <command>
            <name>update</name>
            <description>Update a book from its source</description>
            <arguments>
                <argument>name</argument>
            </arguments>
        </command>
    </command>
    <command>
        <name>parsers</name>
        <description>Parser-related commands</description>
        <command>
            <name>add</name>
            <description>Add a book parser</description>
            <arguments>
                <argument>name</argument>
                <argument>source</argument>
            </arguments>
        </command>
        <command>
            <name>remove</name>
            <description>Remove a book parser</description>
            <arguments>
                <argument>name</argument>
            </arguments>
        </command>
        <command>
            <name>move</name>
            <description>Change the URL of a book parser</description>
            <arguments>
                <argument>name</argument>
                <argument>new URL</argument>
            </arguments>
        </command>
        <command>
            <name>list</name>
            <description>List all book parsers</description>
        </command>
        <command>
            <name>update</name>
            <description>Update a book parser from its source</description>
            <arguments>
                <argument>name</argument>
            </arguments>
        </command>
    </command>
    <command>
        <name>config</name>
        <description>Configuration/settings</description>
        <command>
            <name>get</name>
            <description>Retrieves the value of a configuration value</description>
            <arguments>
                <argument>property</argument>
            </arguments>
        </command>
        <command>
            <name>set</name>
            <description>Sets the value of a configuration value</description>
            <arguments>
                <argument>property</argument>
                <argument>value</argument>
            </arguments>
        </command>
        <command>
            <name>unset</name>
            <description>Resets the value of a configuration value to the default value</description>
            <arguments>
                <argument>property</argument>
            </arguments>
        </command>
        <command>
            <name>list</name>
            <description>Lists all configurable values</description>
        </command>
    </command>
    <option waterfalls="true">
        <flag>-h</flag>
        <flag>--help</flag>
        <description>Provides help for a command or subcommand</description>
    </option>
</command>
