=== liambloom/bjp-checker/src/io/github/liambloom/tests/book/bjp3/args.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="args">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="command" type="command" />
                <xs:element ref="arg" />
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="command">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="subcommand" type="command" />
                <xs:element ref="arg" />
            </xs:choice>
            <!-- Note:  -->
            <xs:element name="help" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:element name="arg">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" maxOccurs="unbounded" type="xs:string" />
                <xs:choice minOccurs="0">
                    <xs:element name="set" type="paramType" />
                    <xs:element ref="param" maxOccurs="unbounded" />
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="param">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required" />
            <xs:attribute name="required" type="xs:boolean" default="false" />
            <xs:attribute name="type" type="paramType" use="required" />
            <!-- add default value, and make way to say "default value is in code" -->
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="paramType">
        <xs:restriction base="xs:string">
            <!-- TODO add some way to make a literal -->
            <!-- for example, the chapter arg should be number(1-18)|"all" -->
            <!-- also add way to make ranges -->
            <!-- also add way to make enum -->
            <xs:enumeration value="number" />
            <xs:enumeration value="file" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== liambloom/bjp-checker/src/main/java/io/github/liambloom/tests/book/bjp3/args.xml
<?xml version="1.0" encoding="UTF-8"?>

<args
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="args.xsd">

    <command>
        <name>check</name>
        <help>No help for you</help>
    </command>

    <arg>
        <name>--chapter</name>
        <name>-c</name>
        <param name="chapter number" type="1-18|all" />
    </arg>

    <help>BJP3 Checker &#169; Liam Bloom 2021</help>
</args>

=== liambloom/bjp-checker/src/io/github/liambloom/tests/book/bjp3/args.xml
<?xml version="1.0" encoding="UTF-8"?>

<args
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="args.xsd">

    <command>
        <name>check</name>
        <help>No help for you</help>
    </command>

    <arg>
        <name>--chapter</name>
        <name>-c</name>
        <param name="foo" required="true" type="no" />
    </arg>

</args>
